### ISSUE TITLE
Not working, destroyed a table

### ISSUE THREAD

**Issue by nmaxcom** [WaleedAshraf/migrating#2]
Granted, I should've taken a peek at the code before running it.

I don't know what or how happened,  I just want to move on from this Sequelize migration nightmare, but your app dropped an entire table.

To be precise, I run migrating down sequelize pg DB_URL

I had 4 tables and now I have one. There hasn't been any file created.

Don't take it the wrong way but this tiny app is not very well coded. Why would you npm install the db driver every-single-time the app is run? That just makes no sense. Just check first if it's there and then maybe install it.

That's just a no brainer but the whole idea is flawed IMHO.

Thank apollo for backups...

**Comment by WaleedAshraf** [comment]
@nmaxcom you are right. It's not tested at all and not production-ready. I'll add a note to that.

I'm not sure why/how it deleted the tables. It has nothing to do with this lib. It just installs the original knex/sequelize libs and runs the command.

Maybe if you can provide more details, we can fix it.

For installing the packages every time. Yup, that is not needed every time, but as far as I know, npm is smart enough, if you already have the package installed, npm will quickly check it rather than install everything from start.

**Comment by nmaxcom** [comment]
> I'm not sure why/how it deleted the tables. It has nothing to do with this lib. It just installs the original knex/sequelize libs and runs the command.

I don't know either. If I had time I'd see what SQL query is actually being sent to the db.

> For installing the packages every time. Yup, that is not needed every time, but as far as I know, npm is smart enough, if you already have the package installed, npm will quickly check it rather than install everything from start.

It didn't happen to me (zsh on iTerm, all parties updated). You could easily run a terminal command: `npm list thepackage || npm install thepackage`, since `npm list` returns an error code if it's not installed.

If I ever had time I'd like to create a "complete" solution to have the db, the models and the migration files all in sync and easy to generate and deploy. As it stands right now, the way Sequelize works with that is embarrassing.

**Comment by WaleedAshraf** [comment]
👍 
I'll close this issue for now as nothing needs to be done here.
